#!/usr/bin/env python3
"""Generate an extra-tools file (C: composition + distractors) for
`agentlego-server start --extra <file>`.

Emits variants/compose/<variant_id>/extra_tools.py containing:
  - macro-tools that chain two primitive tools; the inner calls go through the
    PROXY (env GTA_PROXY_URL_INTERNAL, default http://127.0.0.1:16281) so all
    probe modes still apply to the inner primitives;
  - distractor tools with plausible names/descriptions returning
    useless-but-valid outputs (no GPU, deterministic).

Expose them to the agent with:  export GTA_EXTRA_TOOLS=<comma list of names>
(the per-task GTA resource list does not include them otherwise).

Usage:
  python gen_extra_tools.py --out variants/compose --macros --n-distractors 5 --seed 0
"""
import argparse
import json
import random
from pathlib import Path

HEADER = '''"""Auto-generated by envgen/gen_extra_tools.py — DO NOT EDIT."""
import os
import io
import base64
import requests
from agentlego.types import Annotated, ImageIO, Info
from agentlego.tools.base import BaseTool

PROXY = os.getenv('GTA_PROXY_URL_INTERNAL', 'http://127.0.0.1:16281')


def _post_image_tool(tool, image: ImageIO, **params):
    """Call a primitive tool through the proxy with an image upload."""
    buf = io.BytesIO()
    image.to_pil().save(buf, format='PNG')
    buf.seek(0)
    r = requests.post(f'{PROXY}/{tool}', params=params,
                      files={'image': ('image.png', buf, 'image/png')},
                      headers={'X-GTA-Task-Id': os.getenv('GTA_MACRO_TASK', 'macro')})
    r.raise_for_status()
    return r.json()
'''

MACROS = {
    "LocateThenDescribe": '''

class LocateThenDescribe(BaseTool):
    """A macro tool that first locates an object in the image and then
    describes the attributes of the located region."""

    default_desc = ('Locate an object in the image by description, then '
                    'return the attribute description of the found region.')

    def apply(self,
              image: ImageIO,
              text: Annotated[str, Info('The object to locate.')],
              attribute: Annotated[str, Info('The attribute to describe.')]) -> str:
        bbox = _post_image_tool('TextToBbox', image, text=text)
        if not isinstance(bbox, str):
            bbox = json.dumps(bbox)
        import re as _re
        m = _re.search(r'\\((\\d+),\\s*(\\d+),\\s*(\\d+),\\s*(\\d+)\\)', str(bbox))
        coords = ', '.join(m.groups()) if m else str(bbox)
        desc = _post_image_tool('RegionAttributeDescription', image,
                                bbox=f'({coords})', attribute=attribute)
        return f'bbox: {bbox}\\nregion attribute: {desc}'
''',
    "OCRThenSearch": '''

class OCRThenSearch(BaseTool):
    """A macro tool that reads text from an image and searches the web for it."""

    default_desc = ('Recognize the text on the input image and run a web '
                    'search for the recognized content in one step.')

    def apply(self, image: ImageIO) -> str:
        ocr = _post_image_tool('OCR', image)
        query = str(ocr)[:200]
        r = requests.post(f'{PROXY}/GoogleSearch', params={'query': query})
        r.raise_for_status()
        return f'ocr: {ocr}\\nsearch: {r.json()}'
''',
}

# Distractor pool: (name, description, output template). Outputs are valid,
# deterministic, format-plausible, and task-useless.
DISTRACTORS = [
    ("ImageMetadataAnalyzer",
     "Analyze the technical metadata of the input image, including camera parameters and compression statistics.",
     "Metadata report: format=JPEG, color_space=sRGB, estimated_iso=200, compression_ratio=0.82, exif_gps=absent."),
    ("ColorPaletteExtractor",
     "Extract the dominant color palette of the input image for design use.",
     "Dominant palette: #6b7280 (34%), #d1d5db (27%), #1f2937 (21%), #f59e0b (18%)."),
    ("SceneComplexityScorer",
     "Score the visual complexity of the image scene on a 0-100 scale.",
     "Scene complexity score: 62/100 (moderate clutter, 7 salient regions)."),
    ("TextSentimentAnalyzer",
     "Analyze the sentiment polarity of the given text.",
     "Sentiment: neutral (confidence 0.78); subjectivity: 0.31."),
    ("LanguageDetector",
     "Detect the language of the given text.",
     "Detected language: English (confidence 0.97)."),
    ("ImageHashGenerator",
     "Compute a perceptual hash fingerprint of the image for deduplication.",
     "Perceptual hash: a94f0c33e1b27d58; hamming-safe radius: 6."),
    ("ReadabilityScorer",
     "Compute readability scores of the given text.",
     "Flesch reading ease: 58.3; grade level: 9.2."),
]

DISTRACTOR_TMPL = '''

class {name}(BaseTool):
    """{desc}"""

    default_desc = {desc_repr}

    def apply(self, {sig}) -> str:
        return {out_repr}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="variants/compose")
    ap.add_argument("--variant-id", default=None)
    ap.add_argument("--macros", action="store_true", help="include macro tools")
    ap.add_argument("--n-distractors", type=int, default=5)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    rng = random.Random(args.seed)
    chosen = rng.sample(DISTRACTORS, min(args.n_distractors, len(DISTRACTORS)))

    vid = args.variant_id or f"macros{int(args.macros)}_d{args.n_distractors}_s{args.seed}"
    d = Path(args.out) / vid
    d.mkdir(parents=True, exist_ok=True)

    src = HEADER + "\nimport json\n"
    names = []
    if args.macros:
        for name, code in MACROS.items():
            src += code
            names.append(name)
    for name, desc, out in chosen:
        image_input = any(k in name for k in ("Image", "Scene", "Color"))
        sig = "image: ImageIO" if image_input else \
              "text: Annotated[str, Info('The input text.')]"
        src += DISTRACTOR_TMPL.format(name=name, desc=desc, desc_repr=repr(desc),
                                      sig=sig, out_repr=repr(out))
        names.append(name)

    (d / "extra_tools.py").write_text(src)
    (d / "meta.json").write_text(json.dumps({
        "variant_id": vid, "family": "compose",
        "macros": args.macros, "distractors": [c[0] for c in chosen],
        "extra_tool_names": names, "seed": args.seed}, indent=1))
    print(f"wrote {d}/extra_tools.py with tools: {', '.join(names)}")
    print(f"export GTA_EXTRA_TOOLS={','.join(names)}")


if __name__ == "__main__":
    main()
