"""Auto-generated by envgen/gen_extra_tools.py — DO NOT EDIT."""
import os
import io
import base64
import requests
from agentlego.types import Annotated, ImageIO, Info
from agentlego.tools.base import BaseTool

PROXY = os.getenv('GTA_PROXY_URL_INTERNAL', 'http://127.0.0.1:16281')


def _post_image_tool(tool, image: ImageIO, **params):
    """Call a primitive tool through the proxy with an image upload."""
    buf = io.BytesIO()
    image.to_pil().save(buf, format='PNG')
    buf.seek(0)
    r = requests.post(f'{PROXY}/{tool}', params=params,
                      files={'image': ('image.png', buf, 'image/png')},
                      headers={'X-GTA-Task-Id': os.getenv('GTA_MACRO_TASK', 'macro')})
    r.raise_for_status()
    return r.json()

import json


class LocateThenDescribe(BaseTool):
    """A macro tool that first locates an object in the image and then
    describes the attributes of the located region."""

    default_desc = ('Locate an object in the image by description, then '
                    'return the attribute description of the found region.')

    def apply(self,
              image: ImageIO,
              text: Annotated[str, Info('The object to locate.')],
              attribute: Annotated[str, Info('The attribute to describe.')]) -> str:
        bbox = _post_image_tool('TextToBbox', image, text=text)
        if not isinstance(bbox, str):
            bbox = json.dumps(bbox)
        import re as _re
        m = _re.search(r'\((\d+),\s*(\d+),\s*(\d+),\s*(\d+)\)', str(bbox))
        coords = ', '.join(m.groups()) if m else str(bbox)
        desc = _post_image_tool('RegionAttributeDescription', image,
                                bbox=f'({coords})', attribute=attribute)
        return f'bbox: {bbox}\nregion attribute: {desc}'


class OCRThenSearch(BaseTool):
    """A macro tool that reads text from an image and searches the web for it."""

    default_desc = ('Recognize the text on the input image and run a web '
                    'search for the recognized content in one step.')

    def apply(self, image: ImageIO) -> str:
        ocr = _post_image_tool('OCR', image)
        query = str(ocr)[:200]
        r = requests.post(f'{PROXY}/GoogleSearch', params={'query': query})
        r.raise_for_status()
        return f'ocr: {ocr}\nsearch: {r.json()}'


class ReadabilityScorer(BaseTool):
    """Compute readability scores of the given text."""

    default_desc = 'Compute readability scores of the given text.'

    def apply(self, text: Annotated[str, Info('The input text.')]) -> str:
        return 'Flesch reading ease: 58.3; grade level: 9.2.'


class TextSentimentAnalyzer(BaseTool):
    """Analyze the sentiment polarity of the given text."""

    default_desc = 'Analyze the sentiment polarity of the given text.'

    def apply(self, text: Annotated[str, Info('The input text.')]) -> str:
        return 'Sentiment: neutral (confidence 0.78); subjectivity: 0.31.'


class ImageHashGenerator(BaseTool):
    """Compute a perceptual hash fingerprint of the image for deduplication."""

    default_desc = 'Compute a perceptual hash fingerprint of the image for deduplication.'

    def apply(self, image: ImageIO) -> str:
        return 'Perceptual hash: a94f0c33e1b27d58; hamming-safe radius: 6.'


class ImageMetadataAnalyzer(BaseTool):
    """Analyze the technical metadata of the input image, including camera parameters and compression statistics."""

    default_desc = 'Analyze the technical metadata of the input image, including camera parameters and compression statistics.'

    def apply(self, image: ImageIO) -> str:
        return 'Metadata report: format=JPEG, color_space=sRGB, estimated_iso=200, compression_ratio=0.82, exif_gps=absent.'


class ColorPaletteExtractor(BaseTool):
    """Extract the dominant color palette of the input image for design use."""

    default_desc = 'Extract the dominant color palette of the input image for design use.'

    def apply(self, image: ImageIO) -> str:
        return 'Dominant palette: #6b7280 (34%), #d1d5db (27%), #1f2937 (21%), #f59e0b (18%).'
